"""Kode bahasa (ISO 639-1, sama seperti yang dipakai Whisper) -> nama bahasa dalam Inggris.

Nama bahasa dipakai di prompt TranslateGemma, label dipakai di UI.
"""

LANGUAGES = {
    "id": "Indonesian",
    "en": "English",
    "zh": "Chinese",
    "ja": "Japanese",
    "ko": "Korean",
    "ar": "Arabic",
    "hi": "Hindi",
    "th": "Thai",
    "vi": "Vietnamese",
    "ms": "Malay",
    "tl": "Tagalog",
    "jw": "Javanese",
    "su": "Sundanese",
    "fr": "French",
    "de": "German",
    "es": "Spanish",
    "pt": "Portuguese",
    "it": "Italian",
    "nl": "Dutch",
    "ru": "Russian",
    "uk": "Ukrainian",
    "pl": "Polish",
    "cs": "Czech",
    "sk": "Slovak",
    "ro": "Romanian",
    "hu": "Hungarian",
    "el": "Greek",
    "bg": "Bulgarian",
    "hr": "Croatian",
    "sr": "Serbian",
    "sl": "Slovenian",
    "da": "Danish",
    "sv": "Swedish",
    "no": "Norwegian",
    "fi": "Finnish",
    "et": "Estonian",
    "lv": "Latvian",
    "lt": "Lithuanian",
    "tr": "Turkish",
    "fa": "Persian",
    "he": "Hebrew",
    "ur": "Urdu",
    "bn": "Bengali",
    "ta": "Tamil",
    "te": "Telugu",
    "mr": "Marathi",
    "gu": "Gujarati",
    "kn": "Kannada",
    "ml": "Malayalam",
    "pa": "Punjabi",
    "sw": "Swahili",
    "af": "Afrikaans",
    "ca": "Catalan",
    "km": "Khmer",
    "lo": "Lao",
    "my": "Burmese",
}


def language_name(code):
    return LANGUAGES.get(code, code)
